language: elixir
elixir:
- 1.2
otp_release:
- 18.2
sudo: false
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database contest_director_api_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: ZF8Kp5e0MqpqjDP87SQglxBbobwHqtTl9xr4MkySh9x+5tvV92XUxxTgBUQ753XlHNkeGG9J8NMh6o7c6cE2jlsJ8uAjg4hwrK8SZqWeCUzjfV7BnnbRdttgrz0IBmOfk4tc+aiOT94AUJf7VpQaFoHWRoRuUF4sCOWmT7xPi/ENDIjkk+fSMcHUfX7ZwEoxBevInpDFGAUwTQwVuk+je1MXNnd9CIOABIX6xliv17yS+AcqHQ7VxGRFJt1K1GrZpssYc1F0rJaNWhdDlrzA5yMqoN85M3mSiRnQnob0omUh4grlrYdVrGA/nhsUd4DFIqsrePznS2H/Y831pPHf39S0UspUmj7NAmnZXoJaXqA9uzUElKZwbV+duHrHowGJwJU5PyxxXtzSZoAWj1Dum4btN8S9eOO/ELnjAMZS1/CJYPME7/EbDM3umK9QOuUoDtBlRt4XXnF/5xzoUvwqlauRVB0hCctza1H8xAWPIk7IbNaz0sn5sN4zlPQkehrqNcU88kRBo6tvgCTGBB2C1RM47yzMOv6OeTJklMysoKluR2KFes1nLw9jLnAqQhfP8NE6UqngkWIt8pi2pS8+OjovJyrQ0QsuyZUr0H6hlKsnZ1rOkhgL9nFJJhSnNssa/vtjoymmobl9jgsivBPJtRcSlSO6eoUOeWoY6zIWHTw=
  app: shielded-peak-76475
  on:
    repo: DanMonroe/contest_director_api
